#ifndef CT_C24_LW_LIBRARIES_CEPEXAAA_CHECKEXCEPTION_H
#define CT_C24_LW_LIBRARIES_CEPEXAAA_CHECKEXCEPTION_H
int check_file_extension(const char* filename);
#endif //CT_C24_LW_LIBRARIES_CEPEXAAA_CHECKEXCEPTION_H
